version: 2

sources:
  - name: data
    schema: gz_raw_data
    description: renamed dataset gz_raw_data as data
    tables:
        - name: product
          identifier: raw_gz_product
          description: renamed table
        - name: sales
          identifier: raw_gz_sales
          description: renamed table
          freshness:
            warn_after: {count: 90, period: day}
          loaded_at_field: "CAST(date_date as TIMESTAMP)" 
          
        - name: ship
          identifier: raw_gz_ship
          description: renamed table

        - name: adwords
          identifier: raw_gz_adwords
          
        - name: bing
          identifier: raw_gz_bing
          description: table bing

        - name: criteo
          identifier: raw_gz_criteo

        - name: facebook
          identifier: raw_gz_facebook



models:
  - name: stg_data__product
    columns:
        - name: products_id
          tests:
          - unique
          - not_null
  - name: stg_data__ship
    columns:
      - name: orders_id
        tests:
        - unique
        - not_null
            
  - name: stg_data__sales
    tests:
       - dbt_utils.unique_combination_of_columns:
           combination_of_columns:
              - orders_id
              - products_id  

  - name: stg_data__adwords
    columns:
      - name: date_date
        tests:
        - unique
        - not_null
  
  - name: stg_data__bing
    columns:
      - name: date_date
        tests:
        - unique
        - not_null
  
  - name: stg_data__criteo
    columns:
      - name: date_date
        tests:
        - unique
        - not_null
  
  - name: stg_data__facebook
    columns:
      - name: date_date
        tests:
        - unique
        - not_null