version: 2

sources:
  - name: data
    schema: gz_raw_data
    description: renamed dataset gz_raw_data as data
    tables:
        - name: product
          identifier: raw_gz_product
          description: renamed table
        - name: sales
          identifier: raw_gz_sales
          description: renamed table
        - name: ship
          identifier: raw_gz_ship
          description: renamed table

models:
  - name: stg_data__product.sql
    columns:
        - name: products_id
          tests:
          - unique
          - not_null
  - name: stg_data__ship.sql
    columns:
      - name: orders_id
        tests:
        - unique
        - not_null
            
  - name: stg_data__sales.sql
    tests:
       - dbt_utils.unique_combination_of_columns:
           combination_of_columns:
              - orders_id
              - products_id